// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AdventurersGuild","status":true,"description":"","parameters":{}},
{"name":"QuestSystem","status":false,"description":"","parameters":{}}
];
