// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ResolutionScaler","status":false,"description":"Dynamically resizes the game to fit the screen resolution. v1.0","parameters":{"Screen Width":"1920","Screen Height":"1080"}},
{"name":"ShowEnemyHP","status":true,"description":"Displays enemy HP bar and numbers above their sprites in battle.","parameters":{}},
{"name":"DisablePreBattleAnimation","status":true,"description":"","parameters":{}},
{"name":"FastTravelSystem","status":true,"description":"A fast travel system that allows players to travel to discovered locations.","parameters":{}},
{"name":"MoveMenuLeft","status":false,"description":"Moves the main menu to the top-left corner of the screen.","parameters":{}},
{"name":"MiniMap","status":false,"description":"Adds a minimap to the game, displaying the player's position and discovered locations.","parameters":{}},
{"name":"FastTravelButton","status":false,"description":"Adds a Fast Travel button on the screen for quick access to discovered locations.","parameters":{}},
{"name":"ExpBarHUD","status":true,"description":"Adds an experience bar to the HUD, displaying the player's progress to the next level.","parameters":{}},
{"name":"AdventurersGuild","status":true,"description":"","parameters":{}}
];
