// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"AdventurersGuild","status":true,"description":"A quest and ranking system for the Adventurer's Guild.","parameters":{}},
{"name":"ShowEnemyHP","status":true,"description":"Displays enemy HP bar and numbers above their sprites in battle.","parameters":{}},
{"name":"DisablePreBattleAnimation","status":true,"description":"","parameters":{}},
{"name":"FastTravelSystem","status":true,"description":"A fast travel system that allows players to travel to discovered locations.","parameters":{}}
];
